import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1746648653972 implements MigrationInterface {
    name = 'InitialSchema1746648653972'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`calculation_parameters\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`dataType\` enum ('string', 'number', 'boolean', 'date', 'enum', 'object', 'array') NOT NULL, \`scope\` enum ('input', 'internal', 'output') NOT NULL DEFAULT 'input', \`display_order\` int NOT NULL DEFAULT '0', \`is_required\` tinyint NOT NULL DEFAULT 1, \`default_value\` text NULL, \`min_value\` float NULL, \`max_value\` float NULL, \`regex_pattern\` varchar(255) NULL, \`unit_of_measure\` varchar(255) NULL, \`allowed_values\` text NULL, \`help_text\` text NULL, \`depends_on_parameters\` text NULL, \`formula\` text NULL, \`calculation_template_id\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`calculation_templates\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`type\` enum ('area_volume', 'structural', 'material_estimation', 'budget', 'installation', 'design', 'user_defined') NOT NULL, \`targetProfession\` enum ('architect', 'civil_engineer', 'construction_worker', 'plumber', 'electrician', 'contractor', 'all') NOT NULL, \`formula\` text NOT NULL, \`nec_reference\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`version\` int NOT NULL DEFAULT '1', \`parent_template_id\` varchar(255) NULL, \`source\` enum ('system', 'user', 'community', 'improved') NOT NULL DEFAULT 'system', \`created_by\` varchar(255) NULL, \`is_verified\` tinyint NOT NULL DEFAULT 0, \`verified_by\` varchar(255) NULL, \`verified_at\` datetime NULL, \`is_featured\` tinyint NOT NULL DEFAULT 0, \`usage_count\` int NOT NULL DEFAULT '0', \`average_rating\` decimal(3,2) NOT NULL DEFAULT '0.00', \`rating_count\` int NOT NULL DEFAULT '0', \`tags\` json NULL, \`share_level\` enum ('private', 'organization', 'public') NOT NULL DEFAULT 'private', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_template_usage\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`calculation_template_id\` varchar(255) NOT NULL, \`project_id\` varchar(255) NULL, \`usage_count\` int NOT NULL DEFAULT '1', \`last_used_at\` datetime NOT NULL, \`first_used_at\` datetime NOT NULL, \`is_favorite\` tinyint NOT NULL DEFAULT 0, \`average_completion_time_ms\` int NULL, \`average_calculation_time_ms\` int NULL, \`user_rating\` decimal(3,2) NULL, \`has_provided_feedback\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`type\` enum ('price_change', 'project_delay', 'material_request', 'task_assignment', 'document_upload', 'payment_due', 'inventory_low', 'calculation_complete', 'system_announcement', 'budget_approval') NOT NULL, \`priority\` enum ('low', 'medium', 'high', 'critical') NOT NULL DEFAULT 'medium', \`title\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`is_read\` tinyint NOT NULL DEFAULT 0, \`read_at\` datetime NULL, \`action_url\` varchar(255) NULL, \`action_text\` varchar(255) NULL, \`related_entity_type\` varchar(255) NULL, \`related_entity_id\` varchar(255) NULL, \`expires_at\` datetime NULL, \`icon\` varchar(255) NULL, \`sms_sent\` tinyint NOT NULL DEFAULT 0, \`email_sent\` tinyint NOT NULL DEFAULT 0, \`push_sent\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`material_price_history\` (\`id\` varchar(36) NOT NULL, \`material_id\` varchar(255) NOT NULL, \`price\` decimal(10,2) NOT NULL, \`wholesale_price\` decimal(10,2) NULL, \`wholesale_min_quantity\` int NULL, \`effective_date\` date NOT NULL, \`end_date\` date NULL, \`reason\` enum ('supplier_update', 'market_fluctuation', 'promotion', 'seasonal_change', 'inflation_adjustment', 'bulk_discount', 'other') NULL, \`notes\` text NULL, \`supplier_name\` varchar(255) NULL, \`supplier_id\` varchar(255) NULL, \`recorded_by\` varchar(255) NOT NULL, \`price_change_percentage\` decimal(5,2) NULL, \`is_promotion\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`geographical_zones\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`seismicZone\` enum ('zone_i', 'zone_ii', 'zone_iii', 'zone_iv', 'zone_v') NOT NULL, \`seismic_factor\` decimal(5,3) NOT NULL, \`is_province\` tinyint NOT NULL DEFAULT 1, \`parent_zone_id\` varchar(255) NULL, \`default_soil_type\` enum ('type_a', 'type_b', 'type_c', 'type_d', 'type_e', 'type_f') NULL, \`elevation\` int NULL, \`climate_zone\` varchar(255) NULL, \`wind_speed\` decimal(5,2) NULL, \`rainfall_intensity\` decimal(5,2) NULL, \`snow_load\` decimal(5,2) NULL, \`location_coordinates\` json NULL, \`nec_reference\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`calculation_results\` (\`id\` varchar(36) NOT NULL, \`calculation_template_id\` varchar(255) NOT NULL, \`project_id\` varchar(255) NULL, \`user_id\` varchar(255) NOT NULL, \`inputParameters\` json NOT NULL, \`results\` json NOT NULL, \`is_saved\` tinyint NOT NULL DEFAULT 0, \`name\` varchar(255) NULL, \`notes\` text NULL, \`execution_time_ms\` int NULL, \`was_successful\` tinyint NOT NULL DEFAULT 1, \`error_message\` text NULL, \`used_in_project\` tinyint NOT NULL DEFAULT 0, \`led_to_material_order\` tinyint NOT NULL DEFAULT 0, \`led_to_budget\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`calculation_recommendations\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`project_id\` varchar(255) NULL, \`recommended_template_id\` varchar(255) NOT NULL, \`trigger_template_id\` varchar(255) NULL, \`reason\` enum ('similar_project', 'next_logical_step', 'frequently_used_together', 'improved_version', 'popular_in_profession', 'user_history') NOT NULL, \`score\` decimal(5,4) NOT NULL, \`is_clicked\` tinyint NOT NULL DEFAULT 0, \`is_used\` tinyint NOT NULL DEFAULT 0, \`displayed_at\` datetime NOT NULL, \`clicked_at\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`calculation_feedback\` (\`id\` varchar(36) NOT NULL, \`calculation_template_id\` varchar(255) NOT NULL, \`calculation_result_id\` varchar(255) NULL, \`user_id\` varchar(255) NOT NULL, \`type\` enum ('rating', 'improvement_suggestion', 'error_report', 'comment', 'parameter_suggestion') NOT NULL, \`rating\` decimal(3,2) NULL, \`comment\` text NULL, \`suggestionDetails\` json NULL, \`is_applied\` tinyint NOT NULL DEFAULT 0, \`applied_to_template_id\` varchar(255) NULL, \`is_reviewed\` tinyint NOT NULL DEFAULT 0, \`reviewed_by\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`calculation_improvements\` (\`id\` varchar(36) NOT NULL, \`original_template_id\` varchar(255) NOT NULL, \`improved_template_id\` varchar(255) NULL, \`title\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`proposedChanges\` text NOT NULL, \`status\` enum ('proposed', 'under_review', 'approved', 'implemented', 'rejected') NOT NULL DEFAULT 'proposed', \`proposed_by\` varchar(255) NOT NULL, \`reviewed_by\` varchar(255) NULL, \`feedback_ids\` text NULL, \`is_data_driven\` tinyint NOT NULL DEFAULT 0, \`dataAnalysis\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`calculation_guides\` (\`id\` varchar(36) NOT NULL, \`calculation_template_id\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`created_by\` varchar(255) NOT NULL, \`view_count\` int NOT NULL DEFAULT '0', \`helpful_count\` int NOT NULL DEFAULT '0', \`images\` text NULL, \`video_url\` varchar(255) NULL, \`is_published\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_4f0f50d9922a0ed51c214f5556b\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`mobile_phone\` \`mobile_phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`date_of_birth\` \`date_of_birth\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`national_id\` \`national_id\` varchar(255) NULL COMMENT 'Cédula o RUC'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`gender\` \`gender\` enum ('male', 'female', 'other', 'prefer_not_to_say') NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profile_picture\` \`profile_picture\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`professional_type\` \`professional_type\` enum ('architect', 'civil_engineer', 'constructor', 'contractor', 'electrician', 'plumber', 'designer', 'other') NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`specializations\` \`specializations\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`years_of_experience\` \`years_of_experience\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`education_level\` \`education_level\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`certifications\` \`certifications\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`subscription_expires_at\` \`subscription_expires_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`company\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`company\` json NULL COMMENT 'Información de la empresa del usuario'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`addresses\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`addresses\` json NULL COMMENT 'Direcciones del usuario'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`preferences\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`preferences\` json NULL COMMENT 'Preferencias del usuario'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`stats\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`stats\` json NULL COMMENT 'Estadísticas del usuario'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`interests\` \`interests\` text NULL COMMENT 'Intereses del usuario para recomendaciones'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`referral_code\` \`referral_code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`referred_by\` \`referred_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`socialLinks\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`socialLinks\` json NULL COMMENT 'Links a redes sociales'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verification_token\` \`verification_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_token\` \`password_reset_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_expires\` \`password_reset_expires\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`admin_id\` \`admin_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_88cea2dc9c31951d06437879b40\``);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`icon\` \`icon\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`parent_id\` \`parent_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`specifications\` \`specifications\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`wholesale_price\` \`wholesale_price\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`wholesale_min_quantity\` \`wholesale_min_quantity\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`brand\` \`brand\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`model\` \`model\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`sku\` \`sku\` varchar(255) NULL COMMENT 'Código único de producto'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`barcode\` \`barcode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`image_urls\` \`image_urls\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` DROP COLUMN \`dimensions\``);
        await queryRunner.query(`ALTER TABLE \`materials\` ADD \`dimensions\` json NULL COMMENT 'Dimensiones (largo, ancho, alto, peso)'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`tags\` \`tags\` text NULL COMMENT 'Etiquetas para búsqueda y categorización'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_0841476ce9e40a2604e4d68b022\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_e31033962dc07b8d84a5b7ecb04\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_7a37fb09c5fc8cb685d91ef7e77\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`taskId\` \`taskId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`materialId\` \`materialId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`requesterId\` \`requesterId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_2687b3eaf84c102e4704b294d10\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_9a16d2c86252529f622fa53f1e3\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`start_date\` \`start_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`assigned_to\` \`assigned_to\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`phaseId\` \`phaseId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`assigneeId\` \`assigneeId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`phases\` DROP FOREIGN KEY \`FK_5cc8558954b6360a5b7fb5f45fa\``);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`projectId\` \`projectId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_documents\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` DROP FOREIGN KEY \`FK_ec3099cfe554eeff19bf6fbb952\``);
        await queryRunner.query(`ALTER TABLE \`budget_items\` CHANGE \`category\` \`category\` varchar(255) NULL COMMENT 'Categoría del ítem (materiales, mano de obra, etc.)'`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_budgets\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`responsibilities\` \`responsibilities\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`hourly_rate\` \`hourly_rate\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`allocated_hours\` \`allocated_hours\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`start_date\` \`start_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`type\` \`type\` enum ('residential', 'commercial', 'industrial', 'infrastructure', 'remodeling', 'maintenance', 'other') NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_name\` \`client_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_email\` \`client_email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_phone\` \`client_phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`estimated_completion_date\` \`estimated_completion_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`total_area\` \`total_area\` decimal(10,2) NULL COMMENT 'Área total en metros cuadrados'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`construction_area\` \`construction_area\` decimal(10,2) NULL COMMENT 'Área de construcción en metros cuadrados'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`floors\` \`floors\` int NULL COMMENT 'Número de pisos'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`location\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`location\` json NULL COMMENT 'Coordenadas de ubicación'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`permits\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`permits\` json NULL COMMENT 'Permisos y licencias'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`tags\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`tags\` json NULL COMMENT 'Etiquetas para categorización'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`estimatedBudget\` \`estimatedBudget\` decimal(12,2) NULL COMMENT 'Presupuesto total estimado'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`currentCost\` \`currentCost\` decimal(12,2) NULL COMMENT 'Costo total actual'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_7d269f828eae70d35bffc315669\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_b1efb9ee932ba7548dbab94754f\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_77a611a071acaa0cf60c3fcebc1\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`category_id\` \`category_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`project_type\` \`project_type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`supplier_id\` \`supplier_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`reason\` \`reason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`expires_at\` \`expires_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_14047a1c98dc98ce5b95d897110\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_7a2b54d9d51d59f9a5ac3903145\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_e54cbc691fe8044c9f63eec86bb\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`category_id\` \`category_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`search_query\` \`search_query\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`session_id\` \`session_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`ip_address\` \`ip_address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`user_agent\` \`user_agent\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_9ba18dbe4ea525518c4b32df4b6\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_method\` \`payment_method\` enum ('cash', 'bank_transfer', 'credit_card', 'debit_card', 'check', 'paypal', 'other') NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_reference\` \`payment_reference\` varchar(255) NULL COMMENT 'Número de transacción, cheque, etc.'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_date\` \`payment_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`sri_authorization\` \`sri_authorization\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`sri_access_key\` \`sri_access_key\` varchar(255) NULL COMMENT 'Clave de acceso SRI (para facturación electrónica)'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`electronic_invoice_url\` \`electronic_invoice_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_7fb6895fc8fad9f5200e91abb59\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_f57d843bb46a121d4ebc9722bda\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`invoiceId\` \`invoiceId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`materialId\` \`materialId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_4f0f50d9922a0ed51c214f5556b\` FOREIGN KEY (\`admin_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` ADD CONSTRAINT \`FK_e59b425c829bf7d2ee2ee2aacdf\` FOREIGN KEY (\`calculation_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` ADD CONSTRAINT \`FK_8dafddecd6032a3c7f93152c546\` FOREIGN KEY (\`parent_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` ADD CONSTRAINT \`FK_c00f2503acc369fff5d14531c3d\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_88cea2dc9c31951d06437879b40\` FOREIGN KEY (\`parent_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_0841476ce9e40a2604e4d68b022\` FOREIGN KEY (\`taskId\`) REFERENCES \`tasks\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_e31033962dc07b8d84a5b7ecb04\` FOREIGN KEY (\`materialId\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_7a37fb09c5fc8cb685d91ef7e77\` FOREIGN KEY (\`requesterId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_2687b3eaf84c102e4704b294d10\` FOREIGN KEY (\`phaseId\`) REFERENCES \`phases\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_9a16d2c86252529f622fa53f1e3\` FOREIGN KEY (\`assigneeId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`phases\` ADD CONSTRAINT \`FK_5cc8558954b6360a5b7fb5f45fa\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` ADD CONSTRAINT \`FK_ec3099cfe554eeff19bf6fbb952\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` ADD CONSTRAINT \`FK_c16b0946e07585182fe7589221b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` ADD CONSTRAINT \`FK_d9873261c805370d7cfb46b5050\` FOREIGN KEY (\`calculation_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` ADD CONSTRAINT \`FK_1040ea5eb6a7bc8f68f5aca6856\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_7d269f828eae70d35bffc315669\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_b1efb9ee932ba7548dbab94754f\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_77a611a071acaa0cf60c3fcebc1\` FOREIGN KEY (\`supplier_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_14047a1c98dc98ce5b95d897110\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_7a2b54d9d51d59f9a5ac3903145\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_e54cbc691fe8044c9f63eec86bb\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_9a8a82462cab47c73d25f49261f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` ADD CONSTRAINT \`FK_5141d0fe1bfecb978037e367d6c\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` ADD CONSTRAINT \`FK_a968dc1f591174a862e947a099a\` FOREIGN KEY (\`supplier_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` ADD CONSTRAINT \`FK_733e10acb5c1bd592a7a0f635bb\` FOREIGN KEY (\`recorded_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_9ba18dbe4ea525518c4b32df4b6\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_7fb6895fc8fad9f5200e91abb59\` FOREIGN KEY (\`invoiceId\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_f57d843bb46a121d4ebc9722bda\` FOREIGN KEY (\`materialId\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` ADD CONSTRAINT \`FK_bf764a850e92d2eaba5edfcce06\` FOREIGN KEY (\`calculation_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` ADD CONSTRAINT \`FK_853f129c2e18714b20ae9871d25\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` ADD CONSTRAINT \`FK_b84b1267f6e7af4dcab18280295\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` ADD CONSTRAINT \`FK_2ff71ca0895c390a2e74c1d7e47\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` ADD CONSTRAINT \`FK_85d7e3a9cb392c44061e730bf28\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` ADD CONSTRAINT \`FK_15915155175ad73af1d897a8839\` FOREIGN KEY (\`recommended_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` ADD CONSTRAINT \`FK_282e0117b2315610a378e7afc08\` FOREIGN KEY (\`trigger_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` ADD CONSTRAINT \`FK_eb675391ce00b80ef780f1f10b3\` FOREIGN KEY (\`calculation_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` ADD CONSTRAINT \`FK_6ed14207fe2755c8d2530824eeb\` FOREIGN KEY (\`calculation_result_id\`) REFERENCES \`calculation_results\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` ADD CONSTRAINT \`FK_a39098cde243de3776ade5e88b4\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` ADD CONSTRAINT \`FK_51b6edc66f271d96867617f04a9\` FOREIGN KEY (\`applied_to_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` ADD CONSTRAINT \`FK_7d45c7cf8f9fab12dfeb64198c0\` FOREIGN KEY (\`original_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` ADD CONSTRAINT \`FK_043809e28ff744481f88690fcc4\` FOREIGN KEY (\`improved_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` ADD CONSTRAINT \`FK_8b1278d9d2694a5d628a94c654a\` FOREIGN KEY (\`proposed_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` ADD CONSTRAINT \`FK_16b423eef8496fd15c5a550e726\` FOREIGN KEY (\`reviewed_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_guides\` ADD CONSTRAINT \`FK_36996a12e13bc73d787d9040440\` FOREIGN KEY (\`calculation_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_guides\` ADD CONSTRAINT \`FK_1ab3ec926f27d9c64449b4591f5\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`calculation_guides\` DROP FOREIGN KEY \`FK_1ab3ec926f27d9c64449b4591f5\``);
        await queryRunner.query(`ALTER TABLE \`calculation_guides\` DROP FOREIGN KEY \`FK_36996a12e13bc73d787d9040440\``);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` DROP FOREIGN KEY \`FK_16b423eef8496fd15c5a550e726\``);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` DROP FOREIGN KEY \`FK_8b1278d9d2694a5d628a94c654a\``);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` DROP FOREIGN KEY \`FK_043809e28ff744481f88690fcc4\``);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` DROP FOREIGN KEY \`FK_7d45c7cf8f9fab12dfeb64198c0\``);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` DROP FOREIGN KEY \`FK_51b6edc66f271d96867617f04a9\``);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` DROP FOREIGN KEY \`FK_a39098cde243de3776ade5e88b4\``);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` DROP FOREIGN KEY \`FK_6ed14207fe2755c8d2530824eeb\``);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` DROP FOREIGN KEY \`FK_eb675391ce00b80ef780f1f10b3\``);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` DROP FOREIGN KEY \`FK_282e0117b2315610a378e7afc08\``);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` DROP FOREIGN KEY \`FK_15915155175ad73af1d897a8839\``);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` DROP FOREIGN KEY \`FK_85d7e3a9cb392c44061e730bf28\``);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` DROP FOREIGN KEY \`FK_2ff71ca0895c390a2e74c1d7e47\``);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` DROP FOREIGN KEY \`FK_b84b1267f6e7af4dcab18280295\``);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` DROP FOREIGN KEY \`FK_853f129c2e18714b20ae9871d25\``);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` DROP FOREIGN KEY \`FK_bf764a850e92d2eaba5edfcce06\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_f57d843bb46a121d4ebc9722bda\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_7fb6895fc8fad9f5200e91abb59\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_9ba18dbe4ea525518c4b32df4b6\``);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` DROP FOREIGN KEY \`FK_733e10acb5c1bd592a7a0f635bb\``);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` DROP FOREIGN KEY \`FK_a968dc1f591174a862e947a099a\``);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` DROP FOREIGN KEY \`FK_5141d0fe1bfecb978037e367d6c\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_9a8a82462cab47c73d25f49261f\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_e54cbc691fe8044c9f63eec86bb\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_7a2b54d9d51d59f9a5ac3903145\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_14047a1c98dc98ce5b95d897110\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_77a611a071acaa0cf60c3fcebc1\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_b1efb9ee932ba7548dbab94754f\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_7d269f828eae70d35bffc315669\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` DROP FOREIGN KEY \`FK_1040ea5eb6a7bc8f68f5aca6856\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` DROP FOREIGN KEY \`FK_d9873261c805370d7cfb46b5050\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` DROP FOREIGN KEY \`FK_c16b0946e07585182fe7589221b\``);
        await queryRunner.query(`ALTER TABLE \`budget_items\` DROP FOREIGN KEY \`FK_ec3099cfe554eeff19bf6fbb952\``);
        await queryRunner.query(`ALTER TABLE \`phases\` DROP FOREIGN KEY \`FK_5cc8558954b6360a5b7fb5f45fa\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_9a16d2c86252529f622fa53f1e3\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_2687b3eaf84c102e4704b294d10\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_7a37fb09c5fc8cb685d91ef7e77\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_e31033962dc07b8d84a5b7ecb04\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_0841476ce9e40a2604e4d68b022\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_88cea2dc9c31951d06437879b40\``);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` DROP FOREIGN KEY \`FK_c00f2503acc369fff5d14531c3d\``);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` DROP FOREIGN KEY \`FK_8dafddecd6032a3c7f93152c546\``);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` DROP FOREIGN KEY \`FK_e59b425c829bf7d2ee2ee2aacdf\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_4f0f50d9922a0ed51c214f5556b\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`materialId\` \`materialId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`invoiceId\` \`invoiceId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_f57d843bb46a121d4ebc9722bda\` FOREIGN KEY (\`materialId\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_7fb6895fc8fad9f5200e91abb59\` FOREIGN KEY (\`invoiceId\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`electronic_invoice_url\` \`electronic_invoice_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`sri_access_key\` \`sri_access_key\` varchar(255) NULL COMMENT 'Clave de acceso SRI (para facturación electrónica)' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`sri_authorization\` \`sri_authorization\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_date\` \`payment_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_reference\` \`payment_reference\` varchar(255) NULL COMMENT 'Número de transacción, cheque, etc.' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_method\` \`payment_method\` enum ('cash', 'bank_transfer', 'credit_card', 'debit_card', 'check', 'paypal', 'other') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_9ba18dbe4ea525518c4b32df4b6\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`user_agent\` \`user_agent\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`ip_address\` \`ip_address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`session_id\` \`session_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`search_query\` \`search_query\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`category_id\` \`category_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_e54cbc691fe8044c9f63eec86bb\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_7a2b54d9d51d59f9a5ac3903145\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_14047a1c98dc98ce5b95d897110\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`expires_at\` \`expires_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`reason\` \`reason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`supplier_id\` \`supplier_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`project_type\` \`project_type\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`category_id\` \`category_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_77a611a071acaa0cf60c3fcebc1\` FOREIGN KEY (\`supplier_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_b1efb9ee932ba7548dbab94754f\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_7d269f828eae70d35bffc315669\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`currentCost\` \`currentCost\` decimal(12,2) NULL COMMENT 'Costo total actual' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`estimatedBudget\` \`estimatedBudget\` decimal(12,2) NULL COMMENT 'Presupuesto total estimado' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`tags\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`tags\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Etiquetas para categorización' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`permits\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`permits\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Permisos y licencias' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`location\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`location\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Coordenadas de ubicación' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`floors\` \`floors\` int NULL COMMENT 'Número de pisos' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`construction_area\` \`construction_area\` decimal(10,2) NULL COMMENT 'Área de construcción en metros cuadrados' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`total_area\` \`total_area\` decimal(10,2) NULL COMMENT 'Área total en metros cuadrados' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`estimated_completion_date\` \`estimated_completion_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_phone\` \`client_phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_email\` \`client_email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_name\` \`client_name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`type\` \`type\` enum ('residential', 'commercial', 'industrial', 'infrastructure', 'remodeling', 'maintenance', 'other') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`start_date\` \`start_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`allocated_hours\` \`allocated_hours\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`hourly_rate\` \`hourly_rate\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`responsibilities\` \`responsibilities\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_budgets\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` CHANGE \`category\` \`category\` varchar(255) NULL COMMENT 'Categoría del ítem (materiales, mano de obra, etc.)' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` ADD CONSTRAINT \`FK_ec3099cfe554eeff19bf6fbb952\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_documents\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`projectId\` \`projectId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`phases\` ADD CONSTRAINT \`FK_5cc8558954b6360a5b7fb5f45fa\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`assigneeId\` \`assigneeId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`phaseId\` \`phaseId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`assigned_to\` \`assigned_to\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`start_date\` \`start_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_9a16d2c86252529f622fa53f1e3\` FOREIGN KEY (\`assigneeId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_2687b3eaf84c102e4704b294d10\` FOREIGN KEY (\`phaseId\`) REFERENCES \`phases\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`requesterId\` \`requesterId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`materialId\` \`materialId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`taskId\` \`taskId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_7a37fb09c5fc8cb685d91ef7e77\` FOREIGN KEY (\`requesterId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_e31033962dc07b8d84a5b7ecb04\` FOREIGN KEY (\`materialId\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_0841476ce9e40a2604e4d68b022\` FOREIGN KEY (\`taskId\`) REFERENCES \`tasks\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`tags\` \`tags\` text NULL COMMENT 'Etiquetas para búsqueda y categorización' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` DROP COLUMN \`dimensions\``);
        await queryRunner.query(`ALTER TABLE \`materials\` ADD \`dimensions\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Dimensiones (largo, ancho, alto, peso)' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`image_urls\` \`image_urls\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`barcode\` \`barcode\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`sku\` \`sku\` varchar(255) NULL COMMENT 'Código único de producto' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`model\` \`model\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`brand\` \`brand\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`wholesale_min_quantity\` \`wholesale_min_quantity\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`wholesale_price\` \`wholesale_price\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`specifications\` \`specifications\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`parent_id\` \`parent_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`icon\` \`icon\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_88cea2dc9c31951d06437879b40\` FOREIGN KEY (\`parent_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`admin_id\` \`admin_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_expires\` \`password_reset_expires\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_token\` \`password_reset_token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verification_token\` \`verification_token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`socialLinks\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`socialLinks\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Links a redes sociales' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`referred_by\` \`referred_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`referral_code\` \`referral_code\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`interests\` \`interests\` text NULL COMMENT 'Intereses del usuario para recomendaciones' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`stats\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`stats\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Estadísticas del usuario' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`preferences\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`preferences\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Preferencias del usuario' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`addresses\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`addresses\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Direcciones del usuario' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`company\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`company\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Información de la empresa del usuario' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`subscription_expires_at\` \`subscription_expires_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`certifications\` \`certifications\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`education_level\` \`education_level\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`years_of_experience\` \`years_of_experience\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`specializations\` \`specializations\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`professional_type\` \`professional_type\` enum ('architect', 'civil_engineer', 'constructor', 'contractor', 'electrician', 'plumber', 'designer', 'other') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profile_picture\` \`profile_picture\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`gender\` \`gender\` enum ('male', 'female', 'other', 'prefer_not_to_say') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`national_id\` \`national_id\` varchar(255) NULL COMMENT 'Cédula o RUC' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`date_of_birth\` \`date_of_birth\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`mobile_phone\` \`mobile_phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_4f0f50d9922a0ed51c214f5556b\` FOREIGN KEY (\`admin_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`DROP TABLE \`calculation_guides\``);
        await queryRunner.query(`DROP TABLE \`calculation_improvements\``);
        await queryRunner.query(`DROP TABLE \`calculation_feedback\``);
        await queryRunner.query(`DROP TABLE \`calculation_recommendations\``);
        await queryRunner.query(`DROP TABLE \`calculation_results\``);
        await queryRunner.query(`DROP TABLE \`geographical_zones\``);
        await queryRunner.query(`DROP TABLE \`material_price_history\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`user_template_usage\``);
        await queryRunner.query(`DROP TABLE \`calculation_templates\``);
        await queryRunner.query(`DROP TABLE \`calculation_parameters\``);
    }

}
