import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1746629773844 implements MigrationInterface {
    name = 'InitialSchema1746629773844'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`first_name\` varchar(255) NOT NULL, \`last_name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL, \`mobile_phone\` varchar(255) NULL, \`date_of_birth\` date NULL, \`national_id\` varchar(255) NULL COMMENT 'Cédula o RUC', \`gender\` enum ('male', 'female', 'other', 'prefer_not_to_say') NULL, \`profile_picture\` varchar(255) NULL, \`professional_type\` enum ('architect', 'civil_engineer', 'constructor', 'contractor', 'electrician', 'plumber', 'designer', 'other') NULL, \`specializations\` text NULL, \`years_of_experience\` int NULL, \`education_level\` varchar(255) NULL, \`certifications\` text NULL, \`bio\` text NULL, \`role\` enum ('admin', 'normal', 'seller', 'worker') NOT NULL DEFAULT 'normal', \`subscription_plan\` enum ('free', 'premium', 'enterprise', 'custom') NOT NULL DEFAULT 'free', \`subscription_expires_at\` datetime NULL, \`company\` json NULL COMMENT 'Información de la empresa del usuario', \`addresses\` json NULL COMMENT 'Direcciones del usuario', \`preferences\` json NULL COMMENT 'Preferencias del usuario', \`stats\` json NULL COMMENT 'Estadísticas del usuario', \`interests\` text NULL COMMENT 'Intereses del usuario para recomendaciones', \`referral_code\` varchar(255) NULL, \`referred_by\` varchar(255) NULL, \`socialLinks\` json NULL COMMENT 'Links a redes sociales', \`is_active\` tinyint NOT NULL DEFAULT 1, \`is_verified\` tinyint NOT NULL DEFAULT 0, \`verification_token\` varchar(255) NULL, \`password_reset_token\` varchar(255) NULL, \`password_reset_expires\` datetime NULL, \`admin_id\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`icon\` varchar(255) NULL, \`image_url\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`parent_id\` varchar(255) NULL, \`display_order\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`project_documents\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`type\` enum ('contract', 'blueprint', 'permit', 'invoice', 'report', 'specification', 'photo', 'other') NOT NULL DEFAULT 'other', \`file_path\` varchar(255) NOT NULL, \`file_size\` int NOT NULL COMMENT 'Tamaño en bytes', \`file_type\` varchar(255) NOT NULL COMMENT 'MIME type', \`version\` int NOT NULL DEFAULT '1', \`project_id\` varchar(255) NOT NULL, \`uploaded_by\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`budget_items\` (\`id\` varchar(36) NOT NULL, \`description\` varchar(255) NOT NULL, \`quantity\` decimal(10,2) NOT NULL, \`unit_of_measure\` varchar(255) NOT NULL, \`unit_price\` decimal(10,2) NOT NULL, \`subtotal\` decimal(12,2) NOT NULL, \`category\` varchar(255) NULL COMMENT 'Categoría del ítem (materiales, mano de obra, etc.)', \`budget_id\` varchar(255) NOT NULL, \`material_id\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`project_budgets\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`status\` enum ('draft', 'approved', 'revised', 'executed') NOT NULL DEFAULT 'draft', \`version\` int NOT NULL DEFAULT '1', \`subtotal\` decimal(12,2) NOT NULL, \`taxPercentage\` decimal(5,2) NOT NULL DEFAULT '12.00', \`tax\` decimal(12,2) NOT NULL, \`total\` decimal(12,2) NOT NULL, \`project_id\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`project_team_members\` (\`id\` varchar(36) NOT NULL, \`role\` enum ('project_manager', 'architect', 'engineer', 'foreman', 'worker', 'specialist', 'other') NOT NULL DEFAULT 'worker', \`responsibilities\` text NULL, \`hourly_rate\` decimal(10,2) NULL, \`allocated_hours\` int NULL, \`start_date\` date NULL, \`end_date\` date NULL, \`project_id\` varchar(255) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`projects\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`status\` enum ('planning', 'in_progress', 'on_hold', 'completed', 'cancelled') NOT NULL DEFAULT 'planning', \`type\` enum ('residential', 'commercial', 'industrial', 'infrastructure', 'remodeling', 'maintenance', 'other') NULL, \`client_name\` varchar(255) NULL, \`client_email\` varchar(255) NULL, \`client_phone\` varchar(255) NULL, \`start_date\` date NOT NULL, \`end_date\` date NULL, \`estimated_completion_date\` date NULL, \`completion_percentage\` decimal(5,2) NOT NULL DEFAULT '0.00', \`total_area\` decimal(10,2) NULL COMMENT 'Área total en metros cuadrados', \`construction_area\` decimal(10,2) NULL COMMENT 'Área de construcción en metros cuadrados', \`floors\` int NULL COMMENT 'Número de pisos', \`location\` json NULL COMMENT 'Coordenadas de ubicación', \`is_active\` tinyint NOT NULL DEFAULT 1, \`permits\` json NULL COMMENT 'Permisos y licencias', \`tags\` json NULL COMMENT 'Etiquetas para categorización', \`estimatedBudget\` decimal(12,2) NULL COMMENT 'Presupuesto total estimado', \`currentCost\` decimal(12,2) NULL COMMENT 'Costo total actual', \`user_id\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`phases\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`start_date\` date NOT NULL, \`end_date\` date NULL, \`completion_percentage\` decimal(5,2) NOT NULL DEFAULT '0.00', \`project_id\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`projectId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tasks\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`status\` enum ('pending', 'in_progress', 'completed', 'blocked') NOT NULL DEFAULT 'pending', \`start_date\` date NULL, \`end_date\` date NULL, \`phase_id\` varchar(255) NOT NULL, \`assigned_to\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`phaseId\` varchar(36) NULL, \`assigneeId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`material_requests\` (\`id\` varchar(36) NOT NULL, \`quantity\` int NOT NULL, \`status\` enum ('pending', 'approved', 'delivered', 'rejected') NOT NULL DEFAULT 'pending', \`task_id\` varchar(255) NOT NULL, \`material_id\` varchar(255) NOT NULL, \`requester_id\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`taskId\` varchar(36) NULL, \`materialId\` varchar(36) NULL, \`requesterId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`materials\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`specifications\` text NULL, \`price\` decimal(10,2) NOT NULL, \`wholesale_price\` decimal(10,2) NULL, \`wholesale_min_quantity\` int NULL, \`stock\` int NOT NULL DEFAULT '0', \`min_stock\` int NOT NULL COMMENT 'Stock mínimo para alertas' DEFAULT '0', \`unit_of_measure\` varchar(255) NOT NULL, \`brand\` varchar(255) NULL, \`model\` varchar(255) NULL, \`sku\` varchar(255) NULL COMMENT 'Código único de producto', \`barcode\` varchar(255) NULL, \`image_urls\` text NULL, \`is_featured\` tinyint NOT NULL DEFAULT 0, \`is_active\` tinyint NOT NULL DEFAULT 1, \`dimensions\` json NULL COMMENT 'Dimensiones (largo, ancho, alto, peso)', \`category_id\` varchar(255) NOT NULL, \`seller_id\` varchar(255) NOT NULL, \`tags\` text NULL COMMENT 'Etiquetas para búsqueda y categorización', \`rating\` decimal(3,2) NOT NULL COMMENT 'Calificación promedio (0-5)' DEFAULT '0.00', \`rating_count\` int NOT NULL DEFAULT '0', \`view_count\` int NOT NULL DEFAULT '0', \`order_count\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, UNIQUE INDEX \`IDX_2c638e9b0ddf9b957accdaa911\` (\`sku\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_recommendations\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`type\` enum ('material', 'category', 'project_type', 'supplier') NOT NULL, \`material_id\` varchar(255) NULL, \`category_id\` varchar(255) NULL, \`project_type\` varchar(255) NULL, \`supplier_id\` varchar(255) NULL, \`score\` decimal(5,4) NOT NULL COMMENT 'Puntuación de relevancia (0-1)', \`reason\` text NULL, \`status\` enum ('pending', 'viewed', 'clicked', 'converted', 'dismissed') NOT NULL DEFAULT 'pending', \`expires_at\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_interactions\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`type\` enum ('view', 'search', 'click', 'favorite', 'add_to_cart', 'purchase', 'rate', 'review', 'share', 'download') NOT NULL, \`material_id\` varchar(255) NULL, \`category_id\` varchar(255) NULL, \`project_id\` varchar(255) NULL, \`search_query\` varchar(255) NULL, \`metadata\` json NULL, \`session_id\` varchar(255) NULL, \`ip_address\` varchar(255) NULL, \`user_agent\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoices\` (\`id\` varchar(36) NOT NULL, \`invoice_number\` varchar(255) NOT NULL, \`type\` enum ('sale', 'purchase', 'credit_note', 'debit_note') NOT NULL DEFAULT 'sale', \`issue_date\` date NOT NULL, \`due_date\` date NOT NULL, \`subtotal\` decimal(10,2) NOT NULL, \`taxPercentage\` decimal(5,2) NOT NULL DEFAULT '12.00', \`tax\` decimal(10,2) NOT NULL, \`discount_percentage\` decimal(5,2) NOT NULL DEFAULT '0.00', \`discount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`total\` decimal(10,2) NOT NULL, \`amount_paid\` decimal(10,2) NOT NULL DEFAULT '0.00', \`amount_due\` decimal(10,2) NOT NULL, \`payment_method\` enum ('cash', 'bank_transfer', 'credit_card', 'debit_card', 'check', 'paypal', 'other') NULL, \`payment_reference\` varchar(255) NULL COMMENT 'Número de transacción, cheque, etc.', \`payment_date\` date NULL, \`sri_authorization\` varchar(255) NULL, \`sri_access_key\` varchar(255) NULL COMMENT 'Clave de acceso SRI (para facturación electrónica)', \`electronic_invoice_url\` varchar(255) NULL, \`notes\` text NULL, \`status\` enum ('draft', 'issued', 'sent', 'paid', 'partial', 'overdue', 'cancelled') NOT NULL DEFAULT 'draft', \`client_id\` varchar(255) NOT NULL, \`seller_id\` varchar(255) NOT NULL, \`project_id\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, UNIQUE INDEX \`IDX_d8f8d3788694e1b3f96c42c36f\` (\`invoice_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoice_items\` (\`id\` varchar(36) NOT NULL, \`quantity\` int NOT NULL, \`price\` decimal(10,2) NOT NULL, \`subtotal\` decimal(10,2) NOT NULL, \`tax\` decimal(10,2) NOT NULL, \`total\` decimal(10,2) NOT NULL, \`invoice_id\` varchar(255) NOT NULL, \`material_id\` varchar(255) NULL, \`description\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`invoiceId\` varchar(36) NULL, \`materialId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_4f0f50d9922a0ed51c214f5556b\` FOREIGN KEY (\`admin_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_88cea2dc9c31951d06437879b40\` FOREIGN KEY (\`parent_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_documents\` ADD CONSTRAINT \`FK_ce91a721e078a2d9852b61ad8f2\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_documents\` ADD CONSTRAINT \`FK_b110388cd486948d3265b5bd1d4\` FOREIGN KEY (\`uploaded_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` ADD CONSTRAINT \`FK_c3baf040ebaa2c35a6f5e0fe4d9\` FOREIGN KEY (\`budget_id\`) REFERENCES \`project_budgets\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` ADD CONSTRAINT \`FK_ec3099cfe554eeff19bf6fbb952\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_budgets\` ADD CONSTRAINT \`FK_fa8f2a72a3c21da4d55045ca7ca\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` ADD CONSTRAINT \`FK_c1a8ad2f15c8b55e6f6ab702604\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` ADD CONSTRAINT \`FK_e89a82228cbfdd39876ce6c156b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD CONSTRAINT \`FK_bd55b203eb9f92b0c8390380010\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`phases\` ADD CONSTRAINT \`FK_5cc8558954b6360a5b7fb5f45fa\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_2687b3eaf84c102e4704b294d10\` FOREIGN KEY (\`phaseId\`) REFERENCES \`phases\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_9a16d2c86252529f622fa53f1e3\` FOREIGN KEY (\`assigneeId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_0841476ce9e40a2604e4d68b022\` FOREIGN KEY (\`taskId\`) REFERENCES \`tasks\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_e31033962dc07b8d84a5b7ecb04\` FOREIGN KEY (\`materialId\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_7a37fb09c5fc8cb685d91ef7e77\` FOREIGN KEY (\`requesterId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`materials\` ADD CONSTRAINT \`FK_a342f3b8a3e1af973e7fe5a9ee8\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`materials\` ADD CONSTRAINT \`FK_5b8a3098f5dcf3e2dd209963ffe\` FOREIGN KEY (\`seller_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_b65c00f26f1cceff8a096abdf6f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_7d269f828eae70d35bffc315669\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_b1efb9ee932ba7548dbab94754f\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_77a611a071acaa0cf60c3fcebc1\` FOREIGN KEY (\`supplier_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_8165cbaf68d8c40e80bda6468a7\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_14047a1c98dc98ce5b95d897110\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_7a2b54d9d51d59f9a5ac3903145\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_e54cbc691fe8044c9f63eec86bb\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_5534ba11e10f1a9953cbdaabf16\` FOREIGN KEY (\`client_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_44bb811de7d3cef32f28094ea19\` FOREIGN KEY (\`seller_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_9ba18dbe4ea525518c4b32df4b6\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_7fb6895fc8fad9f5200e91abb59\` FOREIGN KEY (\`invoiceId\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_f57d843bb46a121d4ebc9722bda\` FOREIGN KEY (\`materialId\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_f57d843bb46a121d4ebc9722bda\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_7fb6895fc8fad9f5200e91abb59\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_9ba18dbe4ea525518c4b32df4b6\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_44bb811de7d3cef32f28094ea19\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_5534ba11e10f1a9953cbdaabf16\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_e54cbc691fe8044c9f63eec86bb\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_7a2b54d9d51d59f9a5ac3903145\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_14047a1c98dc98ce5b95d897110\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_8165cbaf68d8c40e80bda6468a7\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_77a611a071acaa0cf60c3fcebc1\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_b1efb9ee932ba7548dbab94754f\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_7d269f828eae70d35bffc315669\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_b65c00f26f1cceff8a096abdf6f\``);
        await queryRunner.query(`ALTER TABLE \`materials\` DROP FOREIGN KEY \`FK_5b8a3098f5dcf3e2dd209963ffe\``);
        await queryRunner.query(`ALTER TABLE \`materials\` DROP FOREIGN KEY \`FK_a342f3b8a3e1af973e7fe5a9ee8\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_7a37fb09c5fc8cb685d91ef7e77\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_e31033962dc07b8d84a5b7ecb04\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_0841476ce9e40a2604e4d68b022\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_9a16d2c86252529f622fa53f1e3\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_2687b3eaf84c102e4704b294d10\``);
        await queryRunner.query(`ALTER TABLE \`phases\` DROP FOREIGN KEY \`FK_5cc8558954b6360a5b7fb5f45fa\``);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP FOREIGN KEY \`FK_bd55b203eb9f92b0c8390380010\``);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` DROP FOREIGN KEY \`FK_e89a82228cbfdd39876ce6c156b\``);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` DROP FOREIGN KEY \`FK_c1a8ad2f15c8b55e6f6ab702604\``);
        await queryRunner.query(`ALTER TABLE \`project_budgets\` DROP FOREIGN KEY \`FK_fa8f2a72a3c21da4d55045ca7ca\``);
        await queryRunner.query(`ALTER TABLE \`budget_items\` DROP FOREIGN KEY \`FK_ec3099cfe554eeff19bf6fbb952\``);
        await queryRunner.query(`ALTER TABLE \`budget_items\` DROP FOREIGN KEY \`FK_c3baf040ebaa2c35a6f5e0fe4d9\``);
        await queryRunner.query(`ALTER TABLE \`project_documents\` DROP FOREIGN KEY \`FK_b110388cd486948d3265b5bd1d4\``);
        await queryRunner.query(`ALTER TABLE \`project_documents\` DROP FOREIGN KEY \`FK_ce91a721e078a2d9852b61ad8f2\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_88cea2dc9c31951d06437879b40\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_4f0f50d9922a0ed51c214f5556b\``);
        await queryRunner.query(`DROP TABLE \`invoice_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_d8f8d3788694e1b3f96c42c36f\` ON \`invoices\``);
        await queryRunner.query(`DROP TABLE \`invoices\``);
        await queryRunner.query(`DROP TABLE \`user_interactions\``);
        await queryRunner.query(`DROP TABLE \`user_recommendations\``);
        await queryRunner.query(`DROP INDEX \`IDX_2c638e9b0ddf9b957accdaa911\` ON \`materials\``);
        await queryRunner.query(`DROP TABLE \`materials\``);
        await queryRunner.query(`DROP TABLE \`material_requests\``);
        await queryRunner.query(`DROP TABLE \`tasks\``);
        await queryRunner.query(`DROP TABLE \`phases\``);
        await queryRunner.query(`DROP TABLE \`projects\``);
        await queryRunner.query(`DROP TABLE \`project_team_members\``);
        await queryRunner.query(`DROP TABLE \`project_budgets\``);
        await queryRunner.query(`DROP TABLE \`budget_items\``);
        await queryRunner.query(`DROP TABLE \`project_documents\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
    }

}
