import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1748666873460 implements MigrationInterface {
    name = 'InitialSchema1748666873460'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_addresses\` CHANGE \`reference\` \`reference\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_4f0f50d9922a0ed51c214f5556b\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`mobile_phone\` \`mobile_phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`date_of_birth\` \`date_of_birth\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`national_id\` \`national_id\` varchar(255) NULL COMMENT 'Cédula o RUC'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`gender\` \`gender\` enum ('male', 'female', 'other', 'prefer_not_to_say') NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profile_picture\` \`profile_picture\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`professional_type\` \`professional_type\` enum ('architect', 'civil_engineer', 'constructor', 'contractor', 'electrician', 'plumber', 'designer', 'other') NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`specializations\` \`specializations\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`years_of_experience\` \`years_of_experience\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`education_level\` \`education_level\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`certifications\` \`certifications\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`subscription_expires_at\` \`subscription_expires_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`company\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`company\` json NULL COMMENT 'Información de la empresa del usuario'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`preferences\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`preferences\` json NULL COMMENT 'Preferencias del usuario'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`stats\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`stats\` json NULL COMMENT 'Estadísticas del usuario'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`interests\` \`interests\` text NULL COMMENT 'Intereses del usuario para recomendaciones'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`referral_code\` \`referral_code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`referred_by\` \`referred_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`socialLinks\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`socialLinks\` json NULL COMMENT 'Links a redes sociales'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verification_token\` \`verification_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_token\` \`password_reset_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_expires\` \`password_reset_expires\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`admin_id\` \`admin_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`two_factor_secret\` \`two_factor_secret\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`recovery_codes\` \`recovery_codes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`location\` \`location\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_88cea2dc9c31951d06437879b40\``);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`icon\` \`icon\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`parent_id\` \`parent_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`specifications\` \`specifications\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`wholesale_price\` \`wholesale_price\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`wholesale_min_quantity\` \`wholesale_min_quantity\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`brand\` \`brand\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`model\` \`model\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`sku\` \`sku\` varchar(255) NULL COMMENT 'Código único de producto'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`barcode\` \`barcode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`image_urls\` \`image_urls\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`materials\` DROP COLUMN \`dimensions\``);
        await queryRunner.query(`ALTER TABLE \`materials\` ADD \`dimensions\` json NULL COMMENT 'Dimensiones (largo, ancho, alto, peso)'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`tags\` \`tags\` text NULL COMMENT 'Etiquetas para búsqueda y categorización'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_0841476ce9e40a2604e4d68b022\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_e31033962dc07b8d84a5b7ecb04\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_7a37fb09c5fc8cb685d91ef7e77\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`taskId\` \`taskId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`materialId\` \`materialId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`requesterId\` \`requesterId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_2687b3eaf84c102e4704b294d10\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_9a16d2c86252529f622fa53f1e3\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`start_date\` \`start_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`assigned_to\` \`assigned_to\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`phaseId\` \`phaseId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`assigneeId\` \`assigneeId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`phases\` DROP FOREIGN KEY \`FK_5cc8558954b6360a5b7fb5f45fa\``);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`projectId\` \`projectId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_documents\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` DROP FOREIGN KEY \`FK_ec3099cfe554eeff19bf6fbb952\``);
        await queryRunner.query(`ALTER TABLE \`budget_items\` CHANGE \`category\` \`category\` varchar(255) NULL COMMENT 'Categoría del ítem (materiales, mano de obra, etc.)'`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_budgets\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`responsibilities\` \`responsibilities\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`hourly_rate\` \`hourly_rate\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`allocated_hours\` \`allocated_hours\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`start_date\` \`start_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`type\` \`type\` enum ('residential', 'commercial', 'industrial', 'infrastructure', 'remodeling', 'maintenance', 'other') NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_name\` \`client_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_email\` \`client_email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_phone\` \`client_phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`estimated_completion_date\` \`estimated_completion_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`total_area\` \`total_area\` decimal(10,2) NULL COMMENT 'Área total en metros cuadrados'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`construction_area\` \`construction_area\` decimal(10,2) NULL COMMENT 'Área de construcción en metros cuadrados'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`floors\` \`floors\` int NULL COMMENT 'Número de pisos'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`location\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`location\` json NULL COMMENT 'Coordenadas de ubicación'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`permits\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`permits\` json NULL COMMENT 'Permisos y licencias'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`tags\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`tags\` json NULL COMMENT 'Etiquetas para categorización'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`estimatedBudget\` \`estimatedBudget\` decimal(12,2) NULL COMMENT 'Presupuesto total estimado'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`currentCost\` \`currentCost\` decimal(12,2) NULL COMMENT 'Costo total actual'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`default_value\` \`default_value\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`min_value\` \`min_value\` float NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`max_value\` \`max_value\` float NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`regex_pattern\` \`regex_pattern\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`unit_of_measure\` \`unit_of_measure\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`allowed_values\` \`allowed_values\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`help_text\` \`help_text\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`depends_on_parameters\` \`depends_on_parameters\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`formula\` \`formula\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` DROP FOREIGN KEY \`FK_8dafddecd6032a3c7f93152c546\``);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` DROP FOREIGN KEY \`FK_c00f2503acc369fff5d14531c3d\``);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` CHANGE \`nec_reference\` \`nec_reference\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` CHANGE \`parent_template_id\` \`parent_template_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` CHANGE \`verified_by\` \`verified_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` CHANGE \`verified_at\` \`verified_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` DROP COLUMN \`tags\``);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` ADD \`tags\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` DROP FOREIGN KEY \`FK_853f129c2e18714b20ae9871d25\``);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` CHANGE \`name\` \`name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` CHANGE \`execution_time_ms\` \`execution_time_ms\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` CHANGE \`error_message\` \`error_message\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` DROP FOREIGN KEY \`FK_50ed9ad3bb787a81b392954b64c\``);
        await queryRunner.query(`DROP INDEX \`IDX_usage_log_period\` ON \`user_template_usage_logs\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` CHANGE \`usage_date\` \`usage_date\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` CHANGE \`ip_address\` \`ip_address\` varchar(45) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` CHANGE \`user_agent\` \`user_agent\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` DROP COLUMN \`input_parameters\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` ADD \`input_parameters\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` DROP COLUMN \`output_results\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` ADD \`output_results\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` CHANGE \`error_message\` \`error_message\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_7d269f828eae70d35bffc315669\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_b1efb9ee932ba7548dbab94754f\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_77a611a071acaa0cf60c3fcebc1\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`category_id\` \`category_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`project_type\` \`project_type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`supplier_id\` \`supplier_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`reason\` \`reason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`expires_at\` \`expires_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_14047a1c98dc98ce5b95d897110\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_7a2b54d9d51d59f9a5ac3903145\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_e54cbc691fe8044c9f63eec86bb\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`category_id\` \`category_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`search_query\` \`search_query\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`session_id\` \`session_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`ip_address\` \`ip_address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`user_agent\` \`user_agent\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` DROP FOREIGN KEY \`FK_1040ea5eb6a7bc8f68f5aca6856\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` CHANGE \`average_completion_time_ms\` \`average_completion_time_ms\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` CHANGE \`average_calculation_time_ms\` \`average_calculation_time_ms\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` CHANGE \`user_rating\` \`user_rating\` decimal(3,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP FOREIGN KEY \`FK_cbb26d53c21e1dfb5de9b395ab6\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP FOREIGN KEY \`FK_5a088977c3e95dbd185a356b4d0\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_templates_source\` ON \`user_calculation_templates\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`long_description\` \`long_description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`original_template_id\` \`original_template_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`source_calculation_result_id\` \`source_calculation_result_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`subcategory\` \`subcategory\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`estimated_time\` \`estimated_time\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`nec_reference\` \`nec_reference\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`tags\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`tags\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`requirements\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`requirements\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`application_cases\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`application_cases\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`limitations\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`limitations\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`shared_with\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`shared_with\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`contributors\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`contributors\` json NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_trending_calculations_period_rank\` ON \`trending_calculations\``);
        await queryRunner.query(`ALTER TABLE \`trending_calculations\` CHANGE \`rank_position\` \`rank_position\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` DROP FOREIGN KEY \`FK_dbe2c5d0c3b4f2b1668a1c0a6fb\``);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` CHANGE \`current_value\` \`current_value\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` CHANGE \`proposed_value\` \`proposed_value\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` CHANGE \`justification\` \`justification\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` DROP COLUMN \`references\``);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` ADD \`references\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` CHANGE \`reviewed_by\` \`reviewed_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` CHANGE \`reviewed_at\` \`reviewed_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`template_ratings\` CHANGE \`comment\` \`comment\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` DROP FOREIGN KEY \`FK_9d9a16ba84129d20dd53ea77882\``);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` DROP FOREIGN KEY \`FK_a3785bcbb47694708263e0c33a8\``);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`detailed_justification\` \`detailed_justification\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`reviewed_by\` \`reviewed_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`reviewed_at\` \`reviewed_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`review_comments\` \`review_comments\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`verified_template_id\` \`verified_template_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` DROP COLUMN \`estimated_impact\``);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` ADD \`estimated_impact\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` DROP COLUMN \`approval_workflow\``);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` ADD \`approval_workflow\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`implementation_notes\` \`implementation_notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`quality_score\` \`quality_score\` decimal(3,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`estimated_delivery_date\` \`estimated_delivery_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`actual_delivery_date\` \`actual_delivery_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`tracking_info\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`tracking_info\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_a21e9d18e98c6f9f489a75027d4\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`material_request_id\` \`material_request_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`read_at\` \`read_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`action_url\` \`action_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`action_text\` \`action_text\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`related_entity_type\` \`related_entity_type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`related_entity_id\` \`related_entity_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`expires_at\` \`expires_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`icon\` \`icon\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_property_definitions\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`material_property_definitions\` DROP COLUMN \`options\``);
        await queryRunner.query(`ALTER TABLE \`material_property_definitions\` ADD \`options\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` CHANGE \`text_value\` \`text_value\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` CHANGE \`number_value\` \`number_value\` decimal(18,6) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` CHANGE \`boolean_value\` \`boolean_value\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` CHANGE \`date_value\` \`date_value\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` CHANGE \`array_value\` \`array_value\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` DROP COLUMN \`json_value\``);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` ADD \`json_value\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` DROP FOREIGN KEY \`FK_a968dc1f591174a862e947a099a\``);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`wholesale_price\` \`wholesale_price\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`wholesale_min_quantity\` \`wholesale_min_quantity\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`reason\` \`reason\` enum ('supplier_update', 'market_fluctuation', 'promotion', 'seasonal_change', 'inflation_adjustment', 'bulk_discount', 'other') NULL`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`supplier_name\` \`supplier_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`supplier_id\` \`supplier_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`price_change_percentage\` \`price_change_percentage\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_9ba18dbe4ea525518c4b32df4b6\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_method\` \`payment_method\` enum ('cash', 'bank_transfer', 'credit_card', 'debit_card', 'check', 'paypal', 'other') NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_reference\` \`payment_reference\` varchar(255) NULL COMMENT 'Número de transacción, cheque, etc.'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_date\` \`payment_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`sri_authorization\` \`sri_authorization\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`sri_access_key\` \`sri_access_key\` varchar(255) NULL COMMENT 'Clave de acceso SRI (para facturación electrónica)'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`electronic_invoice_url\` \`electronic_invoice_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_7fb6895fc8fad9f5200e91abb59\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_f57d843bb46a121d4ebc9722bda\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`invoiceId\` \`invoiceId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`materialId\` \`materialId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`parent_zone_id\` \`parent_zone_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`default_soil_type\` \`default_soil_type\` enum ('type_a', 'type_b', 'type_c', 'type_d', 'type_e', 'type_f') NULL`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`elevation\` \`elevation\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`climate_zone\` \`climate_zone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`wind_speed\` \`wind_speed\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`rainfall_intensity\` \`rainfall_intensity\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`snow_load\` \`snow_load\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` DROP COLUMN \`location_coordinates\``);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` ADD \`location_coordinates\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`nec_reference\` \`nec_reference\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` DROP FOREIGN KEY \`FK_85d7e3a9cb392c44061e730bf28\``);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` DROP FOREIGN KEY \`FK_282e0117b2315610a378e7afc08\``);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` CHANGE \`trigger_template_id\` \`trigger_template_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` CHANGE \`clicked_at\` \`clicked_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` DROP FOREIGN KEY \`FK_6ed14207fe2755c8d2530824eeb\``);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` DROP FOREIGN KEY \`FK_51b6edc66f271d96867617f04a9\``);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` CHANGE \`calculation_result_id\` \`calculation_result_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` CHANGE \`rating\` \`rating\` decimal(3,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` CHANGE \`comment\` \`comment\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` DROP COLUMN \`suggestionDetails\``);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` ADD \`suggestionDetails\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` CHANGE \`applied_to_template_id\` \`applied_to_template_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` CHANGE \`reviewed_by\` \`reviewed_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` DROP FOREIGN KEY \`FK_043809e28ff744481f88690fcc4\``);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` DROP FOREIGN KEY \`FK_16b423eef8496fd15c5a550e726\``);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` CHANGE \`improved_template_id\` \`improved_template_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` CHANGE \`reviewed_by\` \`reviewed_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` CHANGE \`feedback_ids\` \`feedback_ids\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` DROP COLUMN \`dataAnalysis\``);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` ADD \`dataAnalysis\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_guides\` CHANGE \`images\` \`images\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_guides\` CHANGE \`video_url\` \`video_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_comparisons\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`calculation_comparisons\` DROP COLUMN \`comparison_data\``);
        await queryRunner.query(`ALTER TABLE \`calculation_comparisons\` ADD \`comparison_data\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`custom_attribution\` \`custom_attribution\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`contribution_description\` \`contribution_description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`contribution_percentage\` \`contribution_percentage\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`original_creation_date\` \`original_creation_date\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`promotion_date\` \`promotion_date\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`promotion_request_id\` \`promotion_request_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` DROP COLUMN \`metrics_at_promotion\``);
        await queryRunner.query(`ALTER TABLE \`author_credits\` ADD \`metrics_at_promotion\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`badge_earned\` \`badge_earned\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`recognition_level\` \`recognition_level\` enum ('bronze', 'silver', 'gold', 'platinum') NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`approved_by\` \`approved_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`approved_at\` \`approved_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`approval_notes\` \`approval_notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` CHANGE \`external_id\` \`external_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` CHANGE \`account_code\` \`account_code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` CHANGE \`accounting_system\` \`accounting_system\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` CHANGE \`error_message\` \`error_message\` text NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_usage_log_period\` ON \`user_template_usage_logs\` (\`template_id\`, \`template_type\`, \`usage_date\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_user_templates_source\` ON \`user_calculation_templates\` (\`source_type\`, \`original_template_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_trending_calculations_period_rank\` ON \`trending_calculations\` (\`period\`, \`rank_position\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_4f0f50d9922a0ed51c214f5556b\` FOREIGN KEY (\`admin_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_88cea2dc9c31951d06437879b40\` FOREIGN KEY (\`parent_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_0841476ce9e40a2604e4d68b022\` FOREIGN KEY (\`taskId\`) REFERENCES \`tasks\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_e31033962dc07b8d84a5b7ecb04\` FOREIGN KEY (\`materialId\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_7a37fb09c5fc8cb685d91ef7e77\` FOREIGN KEY (\`requesterId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_2687b3eaf84c102e4704b294d10\` FOREIGN KEY (\`phaseId\`) REFERENCES \`phases\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_9a16d2c86252529f622fa53f1e3\` FOREIGN KEY (\`assigneeId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`phases\` ADD CONSTRAINT \`FK_5cc8558954b6360a5b7fb5f45fa\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` ADD CONSTRAINT \`FK_ec3099cfe554eeff19bf6fbb952\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` ADD CONSTRAINT \`FK_8dafddecd6032a3c7f93152c546\` FOREIGN KEY (\`parent_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` ADD CONSTRAINT \`FK_c00f2503acc369fff5d14531c3d\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` ADD CONSTRAINT \`FK_853f129c2e18714b20ae9871d25\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` ADD CONSTRAINT \`FK_50ed9ad3bb787a81b392954b64c\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_7d269f828eae70d35bffc315669\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_b1efb9ee932ba7548dbab94754f\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_77a611a071acaa0cf60c3fcebc1\` FOREIGN KEY (\`supplier_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_14047a1c98dc98ce5b95d897110\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_7a2b54d9d51d59f9a5ac3903145\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_e54cbc691fe8044c9f63eec86bb\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` ADD CONSTRAINT \`FK_1040ea5eb6a7bc8f68f5aca6856\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD CONSTRAINT \`FK_cbb26d53c21e1dfb5de9b395ab6\` FOREIGN KEY (\`original_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD CONSTRAINT \`FK_5a088977c3e95dbd185a356b4d0\` FOREIGN KEY (\`source_calculation_result_id\`) REFERENCES \`calculation_results\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` ADD CONSTRAINT \`FK_dbe2c5d0c3b4f2b1668a1c0a6fb\` FOREIGN KEY (\`reviewed_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` ADD CONSTRAINT \`FK_9d9a16ba84129d20dd53ea77882\` FOREIGN KEY (\`reviewed_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` ADD CONSTRAINT \`FK_a3785bcbb47694708263e0c33a8\` FOREIGN KEY (\`verified_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_a21e9d18e98c6f9f489a75027d4\` FOREIGN KEY (\`material_request_id\`) REFERENCES \`material_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` ADD CONSTRAINT \`FK_a968dc1f591174a862e947a099a\` FOREIGN KEY (\`supplier_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_9ba18dbe4ea525518c4b32df4b6\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_7fb6895fc8fad9f5200e91abb59\` FOREIGN KEY (\`invoiceId\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_f57d843bb46a121d4ebc9722bda\` FOREIGN KEY (\`materialId\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` ADD CONSTRAINT \`FK_85d7e3a9cb392c44061e730bf28\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` ADD CONSTRAINT \`FK_282e0117b2315610a378e7afc08\` FOREIGN KEY (\`trigger_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` ADD CONSTRAINT \`FK_6ed14207fe2755c8d2530824eeb\` FOREIGN KEY (\`calculation_result_id\`) REFERENCES \`calculation_results\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` ADD CONSTRAINT \`FK_51b6edc66f271d96867617f04a9\` FOREIGN KEY (\`applied_to_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` ADD CONSTRAINT \`FK_043809e28ff744481f88690fcc4\` FOREIGN KEY (\`improved_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` ADD CONSTRAINT \`FK_16b423eef8496fd15c5a550e726\` FOREIGN KEY (\`reviewed_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` DROP FOREIGN KEY \`FK_16b423eef8496fd15c5a550e726\``);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` DROP FOREIGN KEY \`FK_043809e28ff744481f88690fcc4\``);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` DROP FOREIGN KEY \`FK_51b6edc66f271d96867617f04a9\``);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` DROP FOREIGN KEY \`FK_6ed14207fe2755c8d2530824eeb\``);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` DROP FOREIGN KEY \`FK_282e0117b2315610a378e7afc08\``);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` DROP FOREIGN KEY \`FK_85d7e3a9cb392c44061e730bf28\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_f57d843bb46a121d4ebc9722bda\``);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` DROP FOREIGN KEY \`FK_7fb6895fc8fad9f5200e91abb59\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_9ba18dbe4ea525518c4b32df4b6\``);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` DROP FOREIGN KEY \`FK_a968dc1f591174a862e947a099a\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_a21e9d18e98c6f9f489a75027d4\``);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` DROP FOREIGN KEY \`FK_a3785bcbb47694708263e0c33a8\``);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` DROP FOREIGN KEY \`FK_9d9a16ba84129d20dd53ea77882\``);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` DROP FOREIGN KEY \`FK_dbe2c5d0c3b4f2b1668a1c0a6fb\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP FOREIGN KEY \`FK_5a088977c3e95dbd185a356b4d0\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP FOREIGN KEY \`FK_cbb26d53c21e1dfb5de9b395ab6\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` DROP FOREIGN KEY \`FK_1040ea5eb6a7bc8f68f5aca6856\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_e54cbc691fe8044c9f63eec86bb\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_7a2b54d9d51d59f9a5ac3903145\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP FOREIGN KEY \`FK_14047a1c98dc98ce5b95d897110\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_77a611a071acaa0cf60c3fcebc1\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_b1efb9ee932ba7548dbab94754f\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_7d269f828eae70d35bffc315669\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` DROP FOREIGN KEY \`FK_50ed9ad3bb787a81b392954b64c\``);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` DROP FOREIGN KEY \`FK_853f129c2e18714b20ae9871d25\``);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` DROP FOREIGN KEY \`FK_c00f2503acc369fff5d14531c3d\``);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` DROP FOREIGN KEY \`FK_8dafddecd6032a3c7f93152c546\``);
        await queryRunner.query(`ALTER TABLE \`budget_items\` DROP FOREIGN KEY \`FK_ec3099cfe554eeff19bf6fbb952\``);
        await queryRunner.query(`ALTER TABLE \`phases\` DROP FOREIGN KEY \`FK_5cc8558954b6360a5b7fb5f45fa\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_9a16d2c86252529f622fa53f1e3\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_2687b3eaf84c102e4704b294d10\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_7a37fb09c5fc8cb685d91ef7e77\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_e31033962dc07b8d84a5b7ecb04\``);
        await queryRunner.query(`ALTER TABLE \`material_requests\` DROP FOREIGN KEY \`FK_0841476ce9e40a2604e4d68b022\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_88cea2dc9c31951d06437879b40\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_4f0f50d9922a0ed51c214f5556b\``);
        await queryRunner.query(`DROP INDEX \`IDX_trending_calculations_period_rank\` ON \`trending_calculations\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_templates_source\` ON \`user_calculation_templates\``);
        await queryRunner.query(`DROP INDEX \`IDX_usage_log_period\` ON \`user_template_usage_logs\``);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` CHANGE \`error_message\` \`error_message\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` CHANGE \`accounting_system\` \`accounting_system\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` CHANGE \`account_code\` \`account_code\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`accounting_transactions\` CHANGE \`external_id\` \`external_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`approval_notes\` \`approval_notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`approved_at\` \`approved_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`approved_by\` \`approved_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`recognition_level\` \`recognition_level\` enum ('bronze', 'silver', 'gold', 'platinum') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`badge_earned\` \`badge_earned\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` DROP COLUMN \`metrics_at_promotion\``);
        await queryRunner.query(`ALTER TABLE \`author_credits\` ADD \`metrics_at_promotion\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`promotion_request_id\` \`promotion_request_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`promotion_date\` \`promotion_date\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`original_creation_date\` \`original_creation_date\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`contribution_percentage\` \`contribution_percentage\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`contribution_description\` \`contribution_description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`author_credits\` CHANGE \`custom_attribution\` \`custom_attribution\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_comparisons\` DROP COLUMN \`comparison_data\``);
        await queryRunner.query(`ALTER TABLE \`calculation_comparisons\` ADD \`comparison_data\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_comparisons\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_guides\` CHANGE \`video_url\` \`video_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_guides\` CHANGE \`images\` \`images\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` DROP COLUMN \`dataAnalysis\``);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` ADD \`dataAnalysis\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` CHANGE \`feedback_ids\` \`feedback_ids\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` CHANGE \`reviewed_by\` \`reviewed_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` CHANGE \`improved_template_id\` \`improved_template_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` ADD CONSTRAINT \`FK_16b423eef8496fd15c5a550e726\` FOREIGN KEY (\`reviewed_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_improvements\` ADD CONSTRAINT \`FK_043809e28ff744481f88690fcc4\` FOREIGN KEY (\`improved_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` CHANGE \`reviewed_by\` \`reviewed_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` CHANGE \`applied_to_template_id\` \`applied_to_template_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` DROP COLUMN \`suggestionDetails\``);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` ADD \`suggestionDetails\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` CHANGE \`comment\` \`comment\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` CHANGE \`rating\` \`rating\` decimal(3,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` CHANGE \`calculation_result_id\` \`calculation_result_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` ADD CONSTRAINT \`FK_51b6edc66f271d96867617f04a9\` FOREIGN KEY (\`applied_to_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_feedback\` ADD CONSTRAINT \`FK_6ed14207fe2755c8d2530824eeb\` FOREIGN KEY (\`calculation_result_id\`) REFERENCES \`calculation_results\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` CHANGE \`clicked_at\` \`clicked_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` CHANGE \`trigger_template_id\` \`trigger_template_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` ADD CONSTRAINT \`FK_282e0117b2315610a378e7afc08\` FOREIGN KEY (\`trigger_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_recommendations\` ADD CONSTRAINT \`FK_85d7e3a9cb392c44061e730bf28\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`nec_reference\` \`nec_reference\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` DROP COLUMN \`location_coordinates\``);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` ADD \`location_coordinates\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`snow_load\` \`snow_load\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`rainfall_intensity\` \`rainfall_intensity\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`wind_speed\` \`wind_speed\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`climate_zone\` \`climate_zone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`elevation\` \`elevation\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`default_soil_type\` \`default_soil_type\` enum ('type_a', 'type_b', 'type_c', 'type_d', 'type_e', 'type_f') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`parent_zone_id\` \`parent_zone_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`geographical_zones\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`materialId\` \`materialId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`invoiceId\` \`invoiceId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_f57d843bb46a121d4ebc9722bda\` FOREIGN KEY (\`materialId\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoice_items\` ADD CONSTRAINT \`FK_7fb6895fc8fad9f5200e91abb59\` FOREIGN KEY (\`invoiceId\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`electronic_invoice_url\` \`electronic_invoice_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`sri_access_key\` \`sri_access_key\` varchar(255) NULL COMMENT 'Clave de acceso SRI (para facturación electrónica)' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`sri_authorization\` \`sri_authorization\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_date\` \`payment_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_reference\` \`payment_reference\` varchar(255) NULL COMMENT 'Número de transacción, cheque, etc.' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` CHANGE \`payment_method\` \`payment_method\` enum ('cash', 'bank_transfer', 'credit_card', 'debit_card', 'check', 'paypal', 'other') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_9ba18dbe4ea525518c4b32df4b6\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`price_change_percentage\` \`price_change_percentage\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`supplier_id\` \`supplier_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`supplier_name\` \`supplier_name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`reason\` \`reason\` enum ('supplier_update', 'market_fluctuation', 'promotion', 'seasonal_change', 'inflation_adjustment', 'bulk_discount', 'other') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`wholesale_min_quantity\` \`wholesale_min_quantity\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` CHANGE \`wholesale_price\` \`wholesale_price\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_price_history\` ADD CONSTRAINT \`FK_a968dc1f591174a862e947a099a\` FOREIGN KEY (\`supplier_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` DROP COLUMN \`json_value\``);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` ADD \`json_value\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` CHANGE \`array_value\` \`array_value\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` CHANGE \`date_value\` \`date_value\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` CHANGE \`boolean_value\` \`boolean_value\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` CHANGE \`number_value\` \`number_value\` decimal(18,6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_property_values\` CHANGE \`text_value\` \`text_value\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_property_definitions\` DROP COLUMN \`options\``);
        await queryRunner.query(`ALTER TABLE \`material_property_definitions\` ADD \`options\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_property_definitions\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`icon\` \`icon\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`expires_at\` \`expires_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`related_entity_id\` \`related_entity_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`related_entity_type\` \`related_entity_type\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`action_text\` \`action_text\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`action_url\` \`action_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`read_at\` \`read_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`material_request_id\` \`material_request_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_a21e9d18e98c6f9f489a75027d4\` FOREIGN KEY (\`material_request_id\`) REFERENCES \`material_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`tracking_info\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`tracking_info\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`actual_delivery_date\` \`actual_delivery_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`estimated_delivery_date\` \`estimated_delivery_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`quality_score\` \`quality_score\` decimal(3,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`implementation_notes\` \`implementation_notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` DROP COLUMN \`approval_workflow\``);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` ADD \`approval_workflow\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` DROP COLUMN \`estimated_impact\``);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` ADD \`estimated_impact\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`verified_template_id\` \`verified_template_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`review_comments\` \`review_comments\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`reviewed_at\` \`reviewed_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`reviewed_by\` \`reviewed_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` CHANGE \`detailed_justification\` \`detailed_justification\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` ADD CONSTRAINT \`FK_a3785bcbb47694708263e0c33a8\` FOREIGN KEY (\`verified_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promotion_requests\` ADD CONSTRAINT \`FK_9d9a16ba84129d20dd53ea77882\` FOREIGN KEY (\`reviewed_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`template_ratings\` CHANGE \`comment\` \`comment\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` CHANGE \`reviewed_at\` \`reviewed_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` CHANGE \`reviewed_by\` \`reviewed_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` DROP COLUMN \`references\``);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` ADD \`references\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` CHANGE \`justification\` \`justification\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` CHANGE \`proposed_value\` \`proposed_value\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` CHANGE \`current_value\` \`current_value\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`template_suggestions\` ADD CONSTRAINT \`FK_dbe2c5d0c3b4f2b1668a1c0a6fb\` FOREIGN KEY (\`reviewed_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`trending_calculations\` CHANGE \`rank_position\` \`rank_position\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`IDX_trending_calculations_period_rank\` ON \`trending_calculations\` (\`period\`, \`rank_position\`)`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`contributors\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`contributors\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`shared_with\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`shared_with\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`limitations\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`limitations\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`application_cases\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`application_cases\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`requirements\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`requirements\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` DROP COLUMN \`tags\``);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD \`tags\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`nec_reference\` \`nec_reference\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`estimated_time\` \`estimated_time\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`subcategory\` \`subcategory\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`source_calculation_result_id\` \`source_calculation_result_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`original_template_id\` \`original_template_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` CHANGE \`long_description\` \`long_description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`IDX_user_templates_source\` ON \`user_calculation_templates\` (\`source_type\`, \`original_template_id\`)`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD CONSTRAINT \`FK_5a088977c3e95dbd185a356b4d0\` FOREIGN KEY (\`source_calculation_result_id\`) REFERENCES \`calculation_results\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_calculation_templates\` ADD CONSTRAINT \`FK_cbb26d53c21e1dfb5de9b395ab6\` FOREIGN KEY (\`original_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` CHANGE \`user_rating\` \`user_rating\` decimal(3,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` CHANGE \`average_calculation_time_ms\` \`average_calculation_time_ms\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` CHANGE \`average_completion_time_ms\` \`average_completion_time_ms\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage\` ADD CONSTRAINT \`FK_1040ea5eb6a7bc8f68f5aca6856\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`user_agent\` \`user_agent\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`ip_address\` \`ip_address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`session_id\` \`session_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`search_query\` \`search_query\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`category_id\` \`category_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_e54cbc691fe8044c9f63eec86bb\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_7a2b54d9d51d59f9a5ac3903145\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_interactions\` ADD CONSTRAINT \`FK_14047a1c98dc98ce5b95d897110\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`expires_at\` \`expires_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`reason\` \`reason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`supplier_id\` \`supplier_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`project_type\` \`project_type\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`category_id\` \`category_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_77a611a071acaa0cf60c3fcebc1\` FOREIGN KEY (\`supplier_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_b1efb9ee932ba7548dbab94754f\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_7d269f828eae70d35bffc315669\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` CHANGE \`error_message\` \`error_message\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` DROP COLUMN \`output_results\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` ADD \`output_results\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` DROP COLUMN \`input_parameters\``);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` ADD \`input_parameters\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` CHANGE \`user_agent\` \`user_agent\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` CHANGE \`ip_address\` \`ip_address\` varchar(45) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` CHANGE \`usage_date\` \`usage_date\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE INDEX \`IDX_usage_log_period\` ON \`user_template_usage_logs\` (\`template_id\`, \`template_type\`, \`usage_date\`)`);
        await queryRunner.query(`ALTER TABLE \`user_template_usage_logs\` ADD CONSTRAINT \`FK_50ed9ad3bb787a81b392954b64c\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` CHANGE \`error_message\` \`error_message\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` CHANGE \`execution_time_ms\` \`execution_time_ms\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` CHANGE \`name\` \`name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` CHANGE \`project_id\` \`project_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_results\` ADD CONSTRAINT \`FK_853f129c2e18714b20ae9871d25\` FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` DROP COLUMN \`tags\``);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` ADD \`tags\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` CHANGE \`verified_at\` \`verified_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` CHANGE \`verified_by\` \`verified_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` CHANGE \`created_by\` \`created_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` CHANGE \`parent_template_id\` \`parent_template_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` CHANGE \`nec_reference\` \`nec_reference\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` ADD CONSTRAINT \`FK_c00f2503acc369fff5d14531c3d\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_templates\` ADD CONSTRAINT \`FK_8dafddecd6032a3c7f93152c546\` FOREIGN KEY (\`parent_template_id\`) REFERENCES \`calculation_templates\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`formula\` \`formula\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`depends_on_parameters\` \`depends_on_parameters\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`help_text\` \`help_text\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`allowed_values\` \`allowed_values\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`unit_of_measure\` \`unit_of_measure\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`regex_pattern\` \`regex_pattern\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`max_value\` \`max_value\` float(12) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`min_value\` \`min_value\` float(12) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calculation_parameters\` CHANGE \`default_value\` \`default_value\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`currentCost\` \`currentCost\` decimal(12,2) NULL COMMENT 'Costo total actual' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`estimatedBudget\` \`estimatedBudget\` decimal(12,2) NULL COMMENT 'Presupuesto total estimado' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`tags\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`tags\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Etiquetas para categorización' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`permits\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`permits\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Permisos y licencias' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`location\``);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`location\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Coordenadas de ubicación' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`floors\` \`floors\` int NULL COMMENT 'Número de pisos' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`construction_area\` \`construction_area\` decimal(10,2) NULL COMMENT 'Área de construcción en metros cuadrados' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`total_area\` \`total_area\` decimal(10,2) NULL COMMENT 'Área total en metros cuadrados' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`estimated_completion_date\` \`estimated_completion_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_phone\` \`client_phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_email\` \`client_email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`client_name\` \`client_name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`type\` \`type\` enum ('residential', 'commercial', 'industrial', 'infrastructure', 'remodeling', 'maintenance', 'other') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`start_date\` \`start_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`allocated_hours\` \`allocated_hours\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`hourly_rate\` \`hourly_rate\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_team_members\` CHANGE \`responsibilities\` \`responsibilities\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_budgets\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` CHANGE \`material_id\` \`material_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` CHANGE \`category\` \`category\` varchar(255) NULL COMMENT 'Categoría del ítem (materiales, mano de obra, etc.)' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`budget_items\` ADD CONSTRAINT \`FK_ec3099cfe554eeff19bf6fbb952\` FOREIGN KEY (\`material_id\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_documents\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`projectId\` \`projectId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`phases\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`phases\` ADD CONSTRAINT \`FK_5cc8558954b6360a5b7fb5f45fa\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`assigneeId\` \`assigneeId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`phaseId\` \`phaseId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`assigned_to\` \`assigned_to\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`start_date\` \`start_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_9a16d2c86252529f622fa53f1e3\` FOREIGN KEY (\`assigneeId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_2687b3eaf84c102e4704b294d10\` FOREIGN KEY (\`phaseId\`) REFERENCES \`phases\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`requesterId\` \`requesterId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`materialId\` \`materialId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`taskId\` \`taskId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` CHANGE \`notes\` \`notes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_7a37fb09c5fc8cb685d91ef7e77\` FOREIGN KEY (\`requesterId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_e31033962dc07b8d84a5b7ecb04\` FOREIGN KEY (\`materialId\`) REFERENCES \`materials\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`material_requests\` ADD CONSTRAINT \`FK_0841476ce9e40a2604e4d68b022\` FOREIGN KEY (\`taskId\`) REFERENCES \`tasks\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`tags\` \`tags\` text NULL COMMENT 'Etiquetas para búsqueda y categorización' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` DROP COLUMN \`dimensions\``);
        await queryRunner.query(`ALTER TABLE \`materials\` ADD \`dimensions\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Dimensiones (largo, ancho, alto, peso)' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`image_urls\` \`image_urls\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`barcode\` \`barcode\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`sku\` \`sku\` varchar(255) NULL COMMENT 'Código único de producto' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`model\` \`model\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`brand\` \`brand\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`wholesale_min_quantity\` \`wholesale_min_quantity\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`wholesale_price\` \`wholesale_price\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`specifications\` \`specifications\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`materials\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`parent_id\` \`parent_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`icon\` \`icon\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_88cea2dc9c31951d06437879b40\` FOREIGN KEY (\`parent_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`location\` \`location\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`recovery_codes\` \`recovery_codes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`two_factor_secret\` \`two_factor_secret\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`admin_id\` \`admin_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_expires\` \`password_reset_expires\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password_reset_token\` \`password_reset_token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verification_token\` \`verification_token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`socialLinks\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`socialLinks\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Links a redes sociales' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`referred_by\` \`referred_by\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`referral_code\` \`referral_code\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`interests\` \`interests\` text NULL COMMENT 'Intereses del usuario para recomendaciones' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`stats\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`stats\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Estadísticas del usuario' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`preferences\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`preferences\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Preferencias del usuario' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`company\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`company\` longtext COLLATE "utf8mb4_bin" NULL COMMENT 'Información de la empresa del usuario' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`subscription_expires_at\` \`subscription_expires_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`certifications\` \`certifications\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`education_level\` \`education_level\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`years_of_experience\` \`years_of_experience\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`specializations\` \`specializations\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`professional_type\` \`professional_type\` enum ('architect', 'civil_engineer', 'constructor', 'contractor', 'electrician', 'plumber', 'designer', 'other') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profile_picture\` \`profile_picture\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`gender\` \`gender\` enum ('male', 'female', 'other', 'prefer_not_to_say') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`national_id\` \`national_id\` varchar(255) NULL COMMENT 'Cédula o RUC' DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`date_of_birth\` \`date_of_birth\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`mobile_phone\` \`mobile_phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_4f0f50d9922a0ed51c214f5556b\` FOREIGN KEY (\`admin_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_addresses\` CHANGE \`reference\` \`reference\` varchar(255) NULL DEFAULT 'NULL'`);
    }

}
